name: Setup Blazium CLI Action

description: >-
  Setup Blazium CLI for use with macOS, Windows, and Linux CI/CD runners.

author: 'Blazium'
branding:
  icon: 'hard-drive'
  color: 'white'
inputs:
  cli-version:
    description: >-
      Blazium CLI version: e.g., 0.0.13, 0.0.14, etc. Must include major, minor, and patch.
    required: false
    default: 0.0.14
  version:
    description: >-
      Blazium Engine version: e.g., 0.1.184, 0.1.188, etc. Must include major, minor, and patch.
    required: true
  path:
    description: >-
      Path to install Blazium CLI to, relative to the current working directory of
      the action.
    default: 'blazium'
  downloads-path:
    description: >-
      Path to download Blazium CLI to, relative to the current working directory of
      the action.
    default: 'downloads'
  bin-path:
    description: >-
      Path for binaries to be installed to, relative to the current working
      directory of the action. This is the path that will be added to the
      system path.
    default: 'bin'
  os:
    description: >-
      Operating system to install Blazium CLI to. Options: Windows, Linux, MacOS
    default: 'linux'
    required: true
  arch:
    description: >-
      Specify the architecture (e.g., x86_64, arm64, arm32, 32bit, 64bit).
    required: true
  platform:
    description: >-
      Specify the platform (e.g., linux, windows, macos).
    required: true
  download_editor:
    description: >-
      Download Blazium CLI Editor
    required: false
    default: 'true'
  download_template:
    description: >-
      Download Blazium CLI Template
    required: false
    default: 'false'
  
runs:
  using: composite
  steps:
    - name: Download Blazium CLI
      shell: bash
      run: |
        mkdir -p ${{ inputs.downloads-path }}
        curl -L -o ${{ inputs.downloads-path }}/blazium-cli https://cdn.blazium.app/cli/${{ inputs.os }}/${{ inputs.cli-version }}/blazium-cli
        chmod +x ${{ inputs.downloads-path }}/blazium-cli
        ls -l ${{ inputs.downloads-path }}

    - name: Move to bin path
      shell: bash
      run: |
        echo "$(pwd)/${{ inputs.downloads-path }}" >> $GITHUB_PATH

    - name: Verify Blazium CLI Installation
      shell: bash
      run: |
        blazium-cli --version

    - name: Blazium CLI Editor
      shell: bash
      run: |
        mkdir -p ${{ inputs.bin-path }}
        blazium-cli --get-version ${{ inputs.version }} --arch ${{ inputs.arch }} --download --editor --platform ${{ inputs.platform }} ${{ inputs.bin-path }}
      if: ${{ inputs.download_editor == 'true' }}

    - name: Blazium CLI Template
      shell: bash
      run: |
        mkdir -p ${{ inputs.bin-path }}
        blazium-cli --get-version ${{ inputs.version }} --arch ${{ inputs.arch }} --download --template --platform ${{ inputs.platform }} ${{ inputs.bin-path }}
      if: ${{ inputs.download_template == 'true' }}

