name: Setup Blazium CLI Action

description: >-
  Setup Blazium CLI for use with macOS, Windows, and Linux CI/CD runners.

author: 'Blazium'
branding:
  icon: 'hard-drive'
  color: 'white'
inputs:
  cli-version:
    description: >-
      Blazium CLI version: e.g., 0.0.13, 0.0.14, etc. Must include major, minor, and patch.
    default: 0.0.14
  version:
    description: >-
      Blazium Engine version: e.g., 0.1.184, 0.1.188, etc. Must include major, minor, and patch.
    required: true
  path:
    description: >-
      Path to install Blazium CLI to, relative to the current working directory of
      the action.
    default: 'blazium'
  downloads-path:
    description: >-
      Path to download Blazium CLI to, relative to the current working directory of
      the action.
    default: 'downloads'
  bin-path:
    description: >-
      Path for binaries to be installed to, relative to the current working
      directory of the action. This is the path that will be added to the
      system path.
    default: 'bin'
  arch:
    description: >-
      Specify the architecture (e.g., x86_64, arm64, arm32, 32bit, 64bit).
    default: ''
  platform:
    description: >-
      Specify the platform (e.g., linux, windows, macos).
    default: ''
  download_editor:
    description: >-
      Download Blazium CLI Editor
    default: 'true'
  download_template:
    description: >-
      Download Blazium CLI Template
    default: 'false'
  download_mono:
    description: >-
      Download Blazium Mono Version
    default: 'false'
  
runs:
  using: composite
  steps:
    - name: Cache Blazium CLI
      id: cache-blazium-cli
      uses: actions/cache@v3
      with:
        path: ${{ inputs.downloads-path }}/cli
        key: ${{ runner.os }}-blazium-cli-${{ inputs.cli-version }}
    - name: Download Blazium CLI
      shell: bash
      run: |
        echo "Runner os is ${{ runner.os }}"
        if [ "${{ runner.os }}" == "Linux" ]; then
          os="linux"
        elif [ "${{ runner.os }}" == "Windows" ]; then
          os="windows"
        else
          os="darwin"
        fi
        mkdir -p ${{ inputs.downloads-path }}/cli
        if [ "${{ steps.cache-blazium-cli.outputs.cache-hit }}" != "true" ]; then
          # If os is windows, use .exe
          if [ "$os" == "windows" ]; then
            curl -L -o ${{ inputs.downloads-path }}/cli/blazium-cli.exe https://cdn.blazium.app/cli/$os/${{ inputs.cli-version }}/blazium-cli.exe
          else
            curl -L -o ${{ inputs.downloads-path }}/cli/blazium-cli https://cdn.blazium.app/cli/$os/${{ inputs.cli-version }}/blazium-cli
          fi
        else
          echo "Using cached Blazium CLI"
          ls ${{ inputs.downloads-path }}/cli
        fi
        file=$(ls ${{ inputs.downloads-path }}/cli)
        BLAZIUM_CLI=${{ inputs.downloads-path }}/cli/$file
        chmod +x $BLAZIUM_CLI
        echo "BLAZIUM_CLI=$BLAZIUM_CLI" >> $GITHUB_ENV

    - name: Verify Blazium CLI Installation
      shell: bash
      run: |
        ${{ env.BLAZIUM_CLI }} --version

    - name: Cache Blazium Editor
      if: ${{ inputs.download_editor == 'true' }}
      id: cache-editor
      uses: actions/cache@v3
      with:
        path: ${{ inputs.bin-path }}/editor
        key: ${{ runner.os }}-blazium-editor-${{ inputs.version }}-${{ inputs.platform }}-${{ inputs.arch }}

    - name: Blazium Editor Download
      if: ${{ inputs.download_editor == 'true'}}
      shell: bash
      run: |
        echo "Runner os is ${{ runner.os }}"
        if [ "${{ runner.os }}" == "Linux" ]; then
          if [ "${{ inputs.platform }}" == "" ]; then
            platform=linux
          else
            platform=${{ inputs.platform }}
          fi
          if [ "${{ inputs.arch }}" == "" ]; then
            arch=x86_64
          else
            arch=${{ inputs.arch }}
          fi
        elif [ "${{ runner.os }}" == "Windows" ]; then
          if [ "${{ inputs.platform }}" == "" ]; then
            platform=windows
          else
            platform=${{ inputs.platform }}
          fi
          if [ "${{ inputs.arch }}" == "" ]; then
            arch=64bit
          else
            arch=${{ inputs.arch }}
          fi
        else
          if [ "${{ inputs.platform }}" == "" ]; then
            platform=macos
          else
            platform=${{ inputs.platform }}
          fi
          if [ "${{ inputs.arch }}" == "" ]; then
            arch=macos
          else
            arch=${{ inputs.arch }}
          fi
        fi
        if [ "${{ inputs.download_mono }}" == "true" ]; then
          mono=" --mono"
        else
          mono=""
        fi
        if [ "${{ steps.cache-editor.outputs.cache-hit }}" != "true" ]; then
          echo "Using platform $platform and arch $arch and mono $mono"
          mkdir -p ${{ inputs.bin-path }}/editor
          ${{ env.BLAZIUM_CLI }} --get-version ${{ inputs.version }} --arch $arch --download --editor --platform $platform$mono ${{ inputs.bin-path }}/editor
          
          echo "Unzipping editor"
          # Unzip 1st time
          file=$(ls ${{ inputs.bin-path }}/editor)
          ls -lah ${{ inputs.bin-path }}/editor
          unzip ${{ inputs.bin-path }}/editor/$file -d ${{ inputs.bin-path }}/editor
          rm ${{ inputs.bin-path }}/editor/$file

          if [ "$platform" == "macos" ]; then
            # Unzip 2nd time
            file=$(ls ${{ inputs.bin-path }}//editor)
            unzip ${{ inputs.bin-path }}/editor/$file -d ${{ inputs.bin-path }}/editor
            rm ${{ inputs.bin-path }}/editor/$file
          fi
          # Move file
          if [ "$platform" == "linux" ]; then
            file=$(ls ${{ inputs.bin-path }}/editor)
            chmod +x ${{ inputs.bin-path }}/editor/$file
            # Rename it to Blazium
            mv ${{ inputs.bin-path }}/editor/$file ${{ inputs.bin-path }}/editor/Blazium
          elif [ "$platform" == "windows" ]; then
            # Find an executable that is NOT a .console.exe
            file=$(find "${{ inputs.bin-path }}/editor" -type f -name '*.exe' ! -name '*.console.exe' | head -n 1)
            # Rename to Blazium.exe
            mv $file ${{ inputs.bin-path }}/editor/Blazium.exe
            ls -lah ${{ inputs.bin-path }}/editor
          fi

        else
          echo "Using cached platform $platform and arch $arch and mono $mono"
          ls ${{ inputs.bin-path }}/editor
        fi
        
        # Add Blazium to PATH
        echo "${{ inputs.bin-path }}/editor" >> $GITHUB_PATH

        # Export Blazium Editor ENV
        if [ "$platform" == "macos" ]; then
          echo "${{ inputs.bin-path }}/editor/Blazium.app/Contents/MacOS" >> $GITHUB_PATH
          echo "BLAZIUM_EDITOR=${{ inputs.bin-path }}/editor/Blazium.app/Contents/MacOS/Blazium" >> $GITHUB_ENV
        elif [ "$platform" == "linux" ]; then
          echo "BLAZIUM_EDITOR=${{ inputs.bin-path }}/editor/Blazium" >> $GITHUB_ENV
        else
          echo "BLAZIUM_EDITOR=${{ inputs.bin-path }}/editor/Blazium.exe" >> $GITHUB_ENV
        fi

    - name: Verify Blazium Editor Installation
      shell: bash
      if: ${{ inputs.download_editor == 'true' }}
      run: |
        ${{ env.BLAZIUM_EDITOR }} --version

    - name: Cache Blazium Template
      if: ${{ inputs.download_template == 'true' }}
      id: cache-template
      uses: actions/cache@v3
      with:
        path: ${{ inputs.bin-path }}/templates
        key: ${{ runner.os }}-blazium-template-${{ inputs.version }}-${{ inputs.platform }}-${{ inputs.arch }}
            
    - name: Blazium Template
      if: ${{ inputs.download_template == 'true' }}
      shell: bash
      run: |
        if [ "${{ runner.os }}" == "Linux" ]; then
          if [ "${{ inputs.platform }}" == "" ]; then
            platform=linux
          else
            platform=${{ inputs.platform }}
          fi
          if [ "${{ inputs.arch }}" == "" ]; then
            arch=x86_64
          else
            arch=${{ inputs.arch }}
          fi
        elif [ "${{ runner.os }}" == "Windows" ]; then
          if [ "${{ inputs.platform }}" == "" ]; then
            platform=windows
          else
            platform=${{ inputs.platform }}
          fi
          if [ "${{ inputs.arch }}" == "" ]; then
            arch=x86_64
          else
            arch=${{ inputs.arch }}
          fi
        else
          if [ "${{ inputs.platform }}" == "" ]; then
            platform=macos
          else
            platform=${{ inputs.platform }}
          fi
          if [ "${{ inputs.arch }}" == "" ]; then
            arch=macos
          else
            arch=${{ inputs.arch }}
          fi
        fi
        if [ "${{ inputs.download_mono }}" == "true" ]; then
          mono=" --mono"
        else
          mono=""
        fi
        echo "Using platform $platform and arch $arch and mono $mono"

        mkdir -p ${{ inputs.bin-path }}/templates
        if [ "${{ steps.cache-template.outputs.cache-hit }}" != "true" ]; then
          ${{ env.BLAZIUM_CLI }} --get-version ${{ inputs.version }} --arch $arch --download --template --platform $platform$mono ${{ inputs.bin-path }}/templates
        else
          echo "Using cached template"
          ls ${{ inputs.bin-path }}/templates
        fi
        file=$(ls ${{ inputs.bin-path }}/templates)
        # Replace - with .
        version_dot=$(echo "${{ inputs.version }}" | sed 's/-/./')
        
        echo "Unzipping template"
        if [ "$platform" == "macos" ]; then
          mkdir -v -p "/Users/runner/Library/Application Support/Blazium/export_templates"
          unzip ${{ inputs.bin-path }}/templates/$file -d "/Users/runner/Library/Application Support/Blazium/export_templates/$version_dot"
          ls "/Users/runner/Library/Application Support/Blazium/export_templates/$version_dot"
          echo "BLAZIUM_TEMPLATE=\"/Users/runner/Library/Application Support/Blazium/export_templates/$version_dot\"" >> $GITHUB_ENV
        elif [ "$platform" == "linux" ]; then
          mkdir -v -p ~/.local/share/blazium/export_templates
          unzip ${{ inputs.bin-path }}/templates/$file -d ~/.local/share/blazium/export_templates/$version_dot
          ls ~/.local/share/blazium/export_templates/$version_dot
          echo "BLAZIUM_TEMPLATE=~/.local/share/blazium/export_templates/$version_dot" >> $GITHUB_ENV
        else
          mkdir -v -p "C:/Users/runner/AppData/Roaming/Blazium/export_templates"
          unzip ${{ inputs.bin-path }}/templates/$file -d "C:/Users/runner/AppData/Roaming/Blazium/export_templates/$version_dot"
          ls "C:/Users/runner/AppData/Roaming/Blazium/export_templates/$version_dot"
          echo "BLAZIUM_TEMPLATE=\"C:/Users/runner/AppData/Roaming/Blazium/export_templates/$version_dot\"" >> $GITHUB_ENV
        fi

