name: Test Download

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [{
          name: ubuntu-latest,
          platform: linux
          }, {
          name: macos-latest,
          platform: darwin
          }, { 
          name: windows-latest,
          platform: windows
          }]
    runs-on: ${{ matrix.os.name }}

    steps:
      - uses: actions/checkout@v4

      - uses: blazium-engine/setup-blazium@master
        name: 🤖 Setup Blazium
        with:
          version: 0.1.184-nightly
          download_template: true
          platform: ${{ matrix.os.platform }}

      - name: 🔬 Verify Setup
        run: |
          Blazium --version
