name: Test Download

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: blazium-engine/setup-blazium@master
        name: 🤖 Setup Blazium
        with:
          version: 0.1.184-nightly
          download_template: true
          platform: ${{ matrix.os }}

      - name: 🔬 Verify Setup
        run: |
          Blazium --version
